### ISSUE TITLE
BSOD

### ISSUE THREAD

**Issue by h8suga** [kkent030315/NoPatchGuardCallback#1]
I have BSOD on Windows 10 x64 1809

**Comment by kkent030315** [comment]
You have to find RVAs (or by signature) by yourself since NT kernel internal functions (and variables) are not exported.
`0xFuncOrVarAddr` - `PsNtosImageBase` = RVA
https://github.com/kkent030315/NoPatchGuardCallback/blob/71d1e9bd805e9e9f61a2acb112fd2880610facf2/noPGcallback/main.h#L39-L42

- `nt!ExAllocateCallback`
- `nt!ExCompareExchangeCallback`
- `nt!PspCreateProcessNotifyRoutine`
- `nt!PspCreateProcessNotifyRoutineCount`

**Comment by ByLafko** [comment]
can you send ntoskrnl.exe from Windows 191206-1406? 
https://github.com/MatrixKung/ntoskrnl

These addresses cannot be found without the same Windows as yours
nt!PspCreateProcessNotifyRoutine
nt!PspCreateProcessNotifyRoutineCount

**Comment by zwkento** [comment]
> These addresses cannot be found without the same Windows as yours

No way. they are exists on ntoskrnl symbol since Windows XP and may older.

```
lkd> dp nt!PspCreateProcessNotifyRoutine
fffff804`464ec120  ffffbc03`1dc5012f ffffbc03`1ddff87f
fffff804`464ec130  ffffbc03`1e007d4f ffffbc03`1e007fbf
fffff804`464ec140  ffffbc03`1e00828f ffffbc03`1e4c205f
fffff804`464ec150  ffffbc03`1e4c256f ffffbc03`1e4c2fef
fffff804`464ec160  ffffbc03`1e881e3f ffffbc03`1e885e5f
fffff804`464ec170  00000000`00000000 00000000`00000000
fffff804`464ec180  00000000`00000000 00000000`00000000
fffff804`464ec190  00000000`00000000 00000000`00000000

lkd> dd nt!PspCreateProcessNotifyRoutineCount
fffff804`4652d9c8  00000005 00000005 00000002 00000001
fffff804`4652d9d8  00000000 00000000 00000000 00000000
fffff804`4652d9e8  00000000 00000000 00000000 00000000
fffff804`4652d9f8  1dc85040 ffffbc03 00000021 00000000
fffff804`4652da08  a6496fc0 ffff928c a644f6c0 ffff928c
fffff804`4652da18  a649f510 ffff928c 0000001d 00000000
fffff804`4652da28  00000018 00000000 00000024 00000000
fffff804`4652da38  4652e290 fffff804 00000000 00000000
```

**Comment by kkent030315** [comment]
> These addresses cannot be found without the same Windows as yours

No way. these  are exist on the ntoskrnl symbol from since Windows XP.

```
lkd> dp nt!PsNtosImageBase l1
fffff804`464fb470  fffff804`45800000 00000000`00000000

lkd> dp nt!PspCreateProcessNotifyRoutine
fffff804`464ec120  ffffbc03`1dc5012f ffffbc03`1ddff87f
fffff804`464ec130  ffffbc03`1e007d4f ffffbc03`1e007fbf
fffff804`464ec140  ffffbc03`1e00828f ffffbc03`1e4c205f
fffff804`464ec150  ffffbc03`1e4c256f ffffbc03`1e4c2fef
fffff804`464ec160  ffffbc03`1e881e3f ffffbc03`1e885e5f
fffff804`464ec170  00000000`00000000 00000000`00000000
fffff804`464ec180  00000000`00000000 00000000`00000000
fffff804`464ec190  00000000`00000000 00000000`00000000

lkd> dd nt!PspCreateProcessNotifyRoutineCount l1
fffff804`4652d9c8  00000005 00000005 00000002 00000001
```

**Comment by ByLafko** [comment]
wow so fast answer, yep I found them thanks

**Comment by kkent030315** [comment]
I'm glad to hear that. :)

**Comment by ByLafko** [comment]
Maybe I was wrong somewhere? After a certain time, I get BSOD
ImageNotifyRoutineExCount  rising when create callback

```
using ExAllocateCallBack = PCALLBACK_ROUTINE_BLOCK(NTAPI*)(PVOID, UINT32);
using ExCompareExchangeCallBack = BOOL(NTAPI*)(PVOID, PVOID, ULONG);

ExAllocateCallBack ExAllocateCallBackPtr = 0;
ExCompareExchangeCallBack ExCompareExchangeCallBackPtr = 0;


        NTSTATUS NpgInitialize()
	{
		NTSTATUS ntStatus = STATUS_SUCCESS;
		PVOID NtosKrnlImageBase = (PVOID)GetKernelBase();

		if (!NtosKrnlImageBase)
		{
			return STATUS_UNSUCCESSFUL;
		}

		PCHAR sig = E("\x48\x89\x5C\x24\x08\x48\x89\x74\x24\x10\x57\x48\x83\xEC\x20\x48\x8B\xFA\x48\x8B\xF1\xBA\x18\x00\x00\x00\xB9\x00\x02\x00\x00\x41\xB8\x43\x62\x72\x62\xE8");
		PCHAR mask = E("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
		PVOID ExAllocateCallBackAddr = utils::FindPatternImage((PCHAR)NtosKrnlImageBase, sig, mask);
		if (!ExAllocateCallBackAddr)
		{
			return STATUS_UNSUCCESSFUL;
		}
		ExAllocateCallBackPtr = (ExAllocateCallBack)((UINT_PTR)ExAllocateCallBackAddr);

		PCHAR sig2 = E("\x48\x89\x5C\x24\x08\x48\x89\x6C\x24\x10\x48\x89\x74\x24\x18\x57\x48\x83\xEC\x20\x49\x8B\xE8\x48\x8B\xFA\x48\x8B\xF1\x48\x85\xD2\x74\x11\xBA\x10");
		PCHAR mask2 = E("xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx");
		PVOID ExCompareExchangeCallBackAddr = utils::FindPatternImage((PCHAR)NtosKrnlImageBase, sig2, mask2);
		if (!ExCompareExchangeCallBackAddr)
		{
			return STATUS_UNSUCCESSFUL;
		}
		ExCompareExchangeCallBackPtr = (ExCompareExchangeCallBack)((UINT_PTR)ExCompareExchangeCallBackAddr);
		if (!ExAllocateCallBackPtr || !ExCompareExchangeCallBackPtr)
		{
			return STATUS_UNSUCCESSFUL;
		}
		return ntStatus;
	}

	NTSTATUS NpgRegisterCallback(PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
	{
		NTSTATUS ntStatus = STATUS_SUCCESS;
		PVOID NtosKrnlImageBase = (PVOID)GetKernelBase();
		if (!NtosKrnlImageBase)
		{
			return STATUS_UNSUCCESSFUL;
		}
		PCALLBACK_ROUTINE_BLOCK CallbackBlock = ExAllocateCallBackPtr(NotifyRoutine, FALSE);

		if (!CallbackBlock)
		{
			return STATUS_INSUFFICIENT_RESOURCES;
		}

		ULONG Counter = 0;

		PCHAR sig3 = E("\x48\x8D\x0D\x00\x00\x00\x00\x45\x33\xC0\x48\x8D\x0C\xD9\x48\x8B\xD7\xE8\x00\x00\x00\xFF\x84\xC0\x0F\x84\xA0\x00\x00\x00\xF0");
		PCHAR mask3 = E("xxx???xxxxxxxxxxxx???xxxxxxxxxx");
		PVOID PsSetLoadImageNotifyRoutineExAddr = utils::FindPatternImage((PCHAR)NtosKrnlImageBase, sig3, mask3);
		if (!PsSetLoadImageNotifyRoutineExAddr)
		{
			return STATUS_UNSUCCESSFUL;
		}
		PVOID PsSetLoadImageNotifyRoutineExCountAddr = (PVOID)((UINT_PTR)PsSetLoadImageNotifyRoutineExAddr + 30);
		PsSetLoadImageNotifyRoutineExAddr = (PVOID)((UINT64)PsSetLoadImageNotifyRoutineExAddr + *(PINT)((PBYTE)PsSetLoadImageNotifyRoutineExAddr + 3) + 7);

		PVOID* PsSetLoadImageNotifyRoutineEx = &*(PVOID*)((UINT_PTR)PsSetLoadImageNotifyRoutineExAddr);

		while (!ExCompareExchangeCallBackPtr(&PsSetLoadImageNotifyRoutineEx[Counter], CallbackBlock, 0))
		{
			Counter++;
			if (Counter >= PSP_CREATE_PROCESS_NOTIFY_MAX)
			{
				return STATUS_INSUFFICIENT_RESOURCES;
			}
		}
		PsSetLoadImageNotifyRoutineExCountAddr = (PVOID)((UINT64)PsSetLoadImageNotifyRoutineExCountAddr + *(PINT)((PBYTE)PsSetLoadImageNotifyRoutineExCountAddr + 3) + 7);
		InterlockedIncrement((volatile LONG*)&*(UINT32*)((UINT_PTR)PsSetLoadImageNotifyRoutineExCountAddr));
		return ntStatus;
	}

	NTSTATUS DispatchDriverEntry(PLOAD_IMAGE_NOTIFY_ROUTINE NotifyRoutine)
	{
		NTSTATUS ntStatus = STATUS_SUCCESS;
		ntStatus = NpgInitialize();

		if (!NT_SUCCESS(ntStatus))
		{
			return ntStatus;
		}
		ntStatus = NpgRegisterCallback(NotifyRoutine);

		if (!NT_SUCCESS(ntStatus))
		{
			return ntStatus;
		}
		return ntStatus;
	}

        NTSTATUS status = utils::DispatchDriverEntry(LoadImageNotifyRoutine);
	if (!NT_SUCCESS(status))
	{
		return status;
	}
	
```

**Comment by zwkento** [comment]
Please include minidump.

**Comment by ByLafko** [comment]
Testing on Windows 11 21H2 22000.51 and Windows 10 19042.1052
[081021-4187-01.zip](https://github.com/kkent030315/NoPatchGuardCallback/files/6960919/081021-4187-01.zip)

**Comment by kkent030315** [comment]
Thank you for the minidump!

```
CRITICAL_STRUCTURE_CORRUPTION (109)

Arguments:
Arg1: a39fdcd99ec06505, Reserved
Arg2: b3b6e95ff1433664, Reserved
Arg3: 0000000000000002, Failure type dependent information
Arg4: 0000000000000018, Type of corrupted region, can be

18  : Kernel notification callout modification
```

As you can see - it's PatchGuard bugcheck.

In fact 21H2 is the special major version. it's similar to Windows 11 Insider.
I think Microsoft implemented to PatchGuard for my method, after publication of this repository.

PatchGuard is now check if the callback entry is within the legitimate address. however, I can still possible to bypass this measure by placing callback routine stub on the legitimate RWX memory in code cave.

Also, we can hijack existing callback routine by inline-hook or some sort of that, if PG does not care about.

**Comment by kkent030315** [comment]
@ByLafko Is it able to test that out on the older version like 1909?

**Comment by ByLafko** [comment]
Yes, I will test
![Screenshot_1](https://user-images.githubusercontent.com/83066306/128858461-f13d468e-3b37-42cd-90b1-51223c18e958.png)

**Comment by kkent030315** [comment]
I have confirmed that this technique is not useful anymore. so I am going to archive this repository.
However as I said early you can easily bypass this by various ways:

- Place jmp stub on the code cave.
- Hijack existing callback routines.
- And more.
  
```cpp
VOID HijackCallbackEntry(ULONG Index)
{
    // just jmp rax mov rax or something
    Hook(&PsSetLoadImageNotifyRoutineEx[Index]);
}
```

Please note that first 0-5 entries are system reserved so make sure you are hijacking third-party driver callback routines. otherwise I think you will get nice BSOD due to unstability problem.

**Comment by kkent030315** [comment]
Callback routine block is

https://github.com/kkent030315/NoPatchGuardCallback/blob/71d1e9bd805e9e9f61a2acb112fd2880610facf2/noPGcallback/main.h#L51-L56

The structure is an entry of `&PsSetLoadImageNotifyRoutineEx[Index]`. e.g., `&PsSetLoadImageNotifyRoutineEx[Index]->Function`

Thank you for your time.
Good Luck!

**Comment by ByLafko** [comment]
> I have confirmed that this technique is not useful anymore. so I am going to archive this repository.
> However as I said early you can easily bypass this by various ways:
> 
> * Place jmp stub on the code cave.
> * Hijack existing callback routines.
> * And more.
> 
> ```c++
> VOID HijackCallbackEntry(ULONG Index)
> {
>     // just jmp rax mov rax or something
>     Hook(&PsSetLoadImageNotifyRoutineEx[Index]);
> }
> ```
> 
> Please note that first 0-5 entries are system reserved so make sure you are hijacking third-party driver callback routines. otherwise I think you will get nice BSOD due to unstability problem.
BSOD on 1909, Thanks for all
